apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    github.com/project-slug: worldcoin/world-id-agent-plugin
  tags: ['code-lang:PLACEHOLDER-ADD-CODE-LANGUAGE']
  description: World ID plugin
  links:
    - title: Linear
      url: PLACEHOLDER-ADD-LINEAR-URL
    - title: Documentation
      url: PLACEHOLDER-ADD-DOCUMENTATION-URL
    - title: Slack
      url: PLACEHOLDER-ADD-SLACK-URL
  name: world-id-agent-plugin
spec:
  lifecycle: production
  owner: team-product-eng-leads
  type: resource
